# Site settings
title: Wpdanblogger - Panduan WordPress dan Blogger
description: Wpdanblogger Adalah Situs Yang Membahas Tentang Tutorial WordPress dan Blogger, Plugins, Theme WordPress Gratis, Template Blogger Gratis
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wpdanblogger.com" # the base hostname & protocol for your site e.g. http://wpdanblogger.com

# User settings
username: wpdanblogger
user_description: Saya Bukan Penulis Maupun Blogger Profesional. Namun, Menulis Dan Ngeblog Adalah Cara Terbaik Saya Untuk Menghabiskan Waktu Luang Dan Menghasilkan Uang
email: wpdanblogger.id@gmail.com
twitter_username: wpdanblogger
github_username:  wpdanblogger
gplus_username:  wpdanblogger
disqus_username: wpdanblogger
linkedin_username: wpdanblogger
facebook_username: wpdanblogger

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
